### ISSUE TITLE
RPM spec - removing source .tar.gz

### ISSUE THREAD

**Issue by neowutran** [QubesOS-contrib/qubes-skeleton#1]
A thing that always seemed a bit weird to me is "Source0"

```
Source0: %{name}-%{version}.tar.gz

%prep
%setup -q

%install
make install-vm DESTDIR=$RPM_BUILD_ROOT
```

It assume that the git repo is compressed to tar.gz, then copied inside the original git repo (done by the qubes builder, if I correctly understood), then is decompressed by the rpmbuilder. 

Played a bit to remove the "Source0".
The main advantages I see are:
- Remove the need for a specific action from qubes-builder (creating the tar.gz and putting it in the correct place ?)
- Remove the need to compress/uncompress anything

(Maybe the "cp" could be replaced by a symlink, but didn't tested)

```
%prep
cp -Rf %{_sourcedir} qubes-skeleton-%{version}

%install
rm -rf $RPM_BUILD_ROOT
cd qubes-skeleton-%{version}
make install-vm DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT
```

**Comment by fepitre** [comment]
This is a standard approach of RPM packaging. Generating proper `src.rpm` needs to list explicitly all the `Source*`. This is why `qubes-builder` generates a proper archive of current component sources in `tar.gz`, in consequence it does not assumes anything (except if other/external component like `xen` are needed). Also, this skeleton is a dummy example of how a RPM (soon Debian) package can be integrated in to qubes-builder pipeline. As this is not an issue, please open a thread on Qubes devel list.
